# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180328_0118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewTag',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.Tag'),
        ),
    ]
