# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180328_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='NewTag',
        ),
    ]
