# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-08 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180407_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.u_loc, width_field='width_field'),
        ),
    ]
