# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20180426_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=3050),
        ),
    ]
